config/routes.rb
Rails.application.routes.draw do
  resources :clients
  root 'publics#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:client_name, :client_address)
    end
end

app/controllers/publics_controller.rb
class PublicsController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/publics_helper.rb
module PublicsHelper
end

app/views/clients/_form.html.erb
<%= form_with(model: client, local: true) do |form| %>
  <% if client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% client.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :client_name %>
    <%= form.text_field :client_name, id: :client_client_name %>
  </div>

  <div class="field">
    <%= form.label :client_address %>
    <%= form.text_area :client_address, id: :client_client_address %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Clients</h1>

<table>
  <thead>
    <tr>
      <th>Client name</th>
      <th>Client address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.client_name %></td>
        <td><%= client.client_address %></td>
        <td><%= link_to 'Show', client %></td>
        <td><%= link_to 'Edit', edit_client_path(client) %></td>
        <td><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Client', new_client_path %>

app/views/clients/new.html.erb
<h1>New Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Back', clients_path %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Client name:</strong>
  <%= @client.client_name %>
</p>

<p>
  <strong>Client address:</strong>
  <%= @client.client_address %>
</p>

<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Workspace</title>
    <%= csrf_meta_tags %>
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style>
body {
  margin:0;
  font-family:Roboto
  color: #FFFFFF;
  background-color: #EFEFEF;
}
.navbar/*.navbar-nav li a*/ {
   background-color: #30C2FF;
   border-color:#30C2FF;
   font-family:Roboto
   color: #FFFFFF;
   min-height: 75px;
   font-weight: bold;
}
.footer {
   position: fixed;
   left: 0;
   bottom: 0;
   width: 100%;
   background-color: #30C2FF;
   color: #FFFFFFs;
   text-align: left;
}
a{
  color:white;
}
</style>
  </head>

  <body>
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#"><font size=6>Trends and Tees</font>
      <br><font size=3> Inventory Management System</font>
    </div>
    <ul class="nav navbar-nav">
      <li><a href="#">Shirt</a></li>
      <li><a href="#">Spool</a></li>
      <li><a href="#">Book</a></li>
      <li><a href="#">Graph</a></li>
      <li><a href="#">Key</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><h2><a href="#">Logged in as IM</a></h2></li>
      <li><a href="#"><span class="glyphicon glyphicon-log-in"></span></a></li>
    </ul>
  </div>
</nav>

<%= yield %>

<div class="footer">
  <p><a href="#"><bold>HOME</bold></a></p>
</div>
  </body>
</html>

app/views/publics/index.html.erb
<h1 style ="text-align:center;">WELCOME!</h1>
<>
<div class ="box1">
    
</div>